# Varible

## Basic variable

In [1]:
nama = 'Sasuke'
umur = '25'

In [2]:
nama

'Sasuke'

In [3]:
type(nama)

str

In [4]:
umur

'25'

In [5]:
umur = 25

In [6]:
type(umur)

int

In [7]:
jomblo = True

In [8]:
type(jomblo)

bool

### Arithmetic Operation

In [9]:
a = 10
b = 5

a + b

15

In [10]:
c = a + b

In [11]:
c

15

c = c + 1

In [12]:
c += 1

In [13]:
c

16

In [14]:
c -= 5

In [15]:
c

11

In [16]:
e = 40
f = 20

print(e * f)
print(e / f)
print(e + f)
print(e - f)
print(e % f)
print(e ** 2)

800
2.0
60
20
0
1600


### String

In [17]:
g = 'Sasuke pergi ke pasar'

print(len(g))
print(g.index('pergi'))
print(g.split(' '))
print(g.lower())
print(g.upper())

21
7
['Sasuke', 'pergi', 'ke', 'pasar']
sasuke pergi ke pasar
SASUKE PERGI KE PASAR


### Convert String to Number

In [18]:
h = '25'
i = int(h)

print(type(h))
print(i)
print(type(i))

<class 'str'>
25
<class 'int'>


### Math Module

In [19]:
import math

print(round(6.4))
print(round(6.8))
print(math.floor(6.8))
print(math.ceil(6.8))

6
7
6
7


## Tuple

In [20]:
tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5, 6, 7 )

print("Print all tuple1: ", tup1)
print("Print all tuple2: ", tup2)
print("Print tuple1 element-0: ", tup1[0])
print("Print tuple1 element-1 until 5: ", tup2[1:5])
print("Join two tuple: ", tup1 + tup2)

Print all tuple1:  ('physics', 'chemistry', 1997, 2000)
Print all tuple2:  (1, 2, 3, 4, 5, 6, 7)
Print tuple1 element-0:  physics
Print tuple1 element-1 until 5:  (2, 3, 4, 5)
Join two tuple:  ('physics', 'chemistry', 1997, 2000, 1, 2, 3, 4, 5, 6, 7)


## List

In [21]:
list1 = [ 'abcd', 786 , 2.23, 'john', 70.2 ]
tinylist = [123, 'john']

print("Print all list: ", list1)
print("Print list element-0: ", list1[0])
print("Print list element-1: ", list1[1])
print("Print list element-1 until 3: ", list1[1:3])
print("Print list element-1 until 4: ",list1[1:4])
print("Print list element-2 until end: ",list1[2:])
print("Print list twice: ",tinylist * 2)
print("Join two list: ", list1 + tinylist, "\n")

Print all list:  ['abcd', 786, 2.23, 'john', 70.2]
Print list element-0:  abcd
Print list element-1:  786
Print list element-1 until 3:  [786, 2.23]
Print list element-1 until 4:  [786, 2.23, 'john']
Print list element-2 until end:  [2.23, 'john', 70.2]
Print list twice:  [123, 'john', 123, 'john']
Join two list:  ['abcd', 786, 2.23, 'john', 70.2, 123, 'john'] 



In [22]:
list1[1] = 'coba'
list1[1]

'coba'

In [23]:
# tuple[1] = 'math'
# tuple[1]

## Dictionary

+ jumlahnya 1: {'key': value}
+ jumlahnya lebih dari 1: {'key1': value1, 'key2': value2, 'key3': {'key3.1': value31, 'key3.2': value32}}

In [24]:
dict1 = {}
dict1['one'] = "This is one"
dict1[2] = "This is two"
tinydict = {'name': 'john','code':6734, 'dept': {'pos': 'sales', 'pos': 'engineering'}}

print("Print dictionary on dict1['one']: ", dict1['one'])
print("Print dictionary on dict1[2]: ",dict1[2])
print("Print dictionary on dict1: ", dict1)
print("Print dictionary on tinydict: ", tinydict)
print("Print tinydict dictionary keys: ", tinydict.keys())
print("Print tinydict dictionary values: ", tinydict.values(), "\n")

Print dictionary on dict1['one']:  This is one
Print dictionary on dict1[2]:  This is two
Print dictionary on dict1:  {'one': 'This is one', 2: 'This is two'}
Print dictionary on tinydict:  {'name': 'john', 'code': 6734, 'dept': {'pos': 'engineering'}}
Print tinydict dictionary keys:  dict_keys(['name', 'code', 'dept'])
Print tinydict dictionary values:  dict_values(['john', 6734, {'pos': 'engineering'}]) 



## Numpy

In [25]:
import numpy as np

In [26]:
my_list = [1, 2, 3, 4, 5]

type(my_list)

list

In [31]:
my_list

[1, 2, 3, 4, 5]

In [29]:
my_list_np = np.array(my_list)

type(my_list_np)

numpy.ndarray

In [30]:
my_list_np

array([1, 2, 3, 4, 5])

In [34]:
my_list_np.shape

(5,)

In [36]:
my_list_matrix = np.array([[1, 2, 7], [3, 4, 6]])

my_list_matrix

array([[1, 2, 7],
       [3, 4, 6]])

In [37]:
my_list_matrix.shape

(2, 3)

In [38]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
mat1 = np.array([[1, 2, 7], [3, 4, 6]])
mat2 = np.array([[2, 5, 8], [6, 4, 6], [7, 5, 6]])

np.dot(mat1, mat2)

array([[63, 48, 62],
       [72, 61, 84]])

In [69]:
mat2

array([[2, 5, 8],
       [6, 4, 6],
       [7, 5, 6]])

In [74]:
mat2.shape

(3, 3)

In [71]:
mat2[:, 0]

array([2, 6, 7])

In [76]:
mat2[1, 0:2]

array([6, 4])

In [77]:
mat2[1][1]

4

## Pandas or DataFrame

In [44]:
import pandas as pd
from numpy.random import randn

df = pd.DataFrame(randn(5,4), index='1 2 3 4 5'.split(), columns='A B C F'.split())

df

A         B         C         F
1  0.553056 -0.184721  0.997666 -0.516128
2 -0.362055 -1.263195 -0.893229  0.382753
3 -1.088320  0.224629 -1.202894  0.889002
4 -0.374347 -2.296519  0.595867  1.917783
5 -0.043042  1.019330 -0.748327 -0.758768

In [45]:
df.size

20

In [46]:
df.shape

(5, 4)

In [47]:
df['A']

1    0.553056
2   -0.362055
3   -1.088320
4   -0.374347
5   -0.043042
Name: A, dtype: float64

In [50]:
df.loc[['2', '3'], ['B', 'C']]

B         C
2 -1.263195 -0.893229
3  0.224629 -1.202894

In [51]:
df.iloc[:, 1]

1   -0.184721
2   -1.263195
3    0.224629
4   -2.296519
5    1.019330
Name: B, dtype: float64

In [54]:
df.iloc[2:4, 0]

3   -1.088320
4   -0.374347
Name: A, dtype: float64

# Logic

In [78]:
nama = 'Sasuke'
umur = 10
jomblo = False

### If

In [57]:
if jomblo == True:
    print("Sasuke jomblo")

### If Else

In [58]:
if jomblo == True:
    print("Sasuke jomblo")
else:
    print("Sasuke tidak jomblo")

Sasuke tidak jomblo


AND 
1 & 1 = True
1 & 0 = False
0 & 1 = False
0 & 0 = False

AND 
1 & 1 = True
1 & 0 = True
0 & 1 = True
0 & 0 = False


## And

In [79]:
if umur > 17:
    print("Sasuke Dewasa")
elif umur > 14 and umur < 17:
    print("Sasuke Remaja")
else:
    print("Sasuke Kecil")

Sasuke Remaja


## Or

In [ ]:
if umur > 17:
    print("Sasuke Dewasa")
elif umur > 14 or umur < 17:
    print("Sasuke Remaja")
else:
    print("Sasuke Kecil")

In [66]:
buah = ["nanas", "apel", "pepaya", "manggis"]

if buah[1] == "manggis":
    print("True")
else:
    print("False")

Bukan manggis


In [67]:
matrix1 = np.array([[1, 2, 7], [3, 4, 6]])

matrix1

array([[1, 2, 7],
       [3, 4, 6]])

In [68]:
if matrix1[1][1] == 4:
    print("True")
else:
    print("False")

True
