# Varible

### Basic variable

In [1]:
nama = 'Sasuke'
umur = '25'

In [2]:
nama

'Sasuke'

In [3]:
type(nama)

str

In [4]:
umur

'25'

In [5]:
umur = 25

In [6]:
type(umur)

int

In [7]:
jomblo = True

In [8]:
type(jomblo)

bool

### Arithmetic Operation

In [9]:
a = 10
b = 5

a + b

15

In [10]:
c = a + b

In [11]:
c

15

c = c + 1

In [12]:
c += 1

In [13]:
c

16

In [14]:
c -= 5

In [15]:
c

11

In [16]:
e = 40
f = 20

print(e * f)
print(e / f)
print(e + f)
print(e - f)
print(e % f)
print(e ** 2)

800
2.0
60
20
0
1600


### String

In [17]:
g = 'Sasuke pergi ke pasar'

print(len(g))
print(g.index('pergi'))
print(g.split(' '))
print(g.lower())
print(g.upper())

21
7
['Sasuke', 'pergi', 'ke', 'pasar']
sasuke pergi ke pasar
SASUKE PERGI KE PASAR


### Convert String to Number

In [18]:
h = '25'
i = int(h)

print(type(h))
print(i)
print(type(i))

<class 'str'>
25
<class 'int'>


### Math Module

In [19]:
import math

print(round(6.4))
print(round(6.8))
print(math.floor(6.8))
print(math.ceil(6.8))

6
7
6
7


### Tuple

In [20]:
tup1 = ('physics', 'chemistry', 1997, 2000)
tup2 = (1, 2, 3, 4, 5, 6, 7 )

print("Print all tuple1: ", tup1)
print("Print all tuple2: ", tup2)
print("Print tuple1 element-0: ", tup1[0])
print("Print tuple1 element-1 until 5: ", tup2[1:5])
print("Join two tuple: ", tup1 + tup2)

Print all tuple1:  ('physics', 'chemistry', 1997, 2000)
Print all tuple2:  (1, 2, 3, 4, 5, 6, 7)
Print tuple1 element-0:  physics
Print tuple1 element-1 until 5:  (2, 3, 4, 5)
Join two tuple:  ('physics', 'chemistry', 1997, 2000, 1, 2, 3, 4, 5, 6, 7)


In [21]:
tup1[1]

'chemistry'

### List

In [22]:
list1 = [ 'abcd', 786 , 2.23, 'john', 70.2 ]
tinylist = [123, 'john']

print("Print all list: ", list1)
print("Print list element-0: ", list1[0])
print("Print list element-1: ", list1[1])
print("Print list element-1 until 3: ", list1[1:3])
print("Print list element-1 until 4: ",list1[1:4])
print("Print list element-2 until end: ",list1[2:])
print("Print list twice: ",tinylist * 2)
print("Join two list: ", list1 + tinylist, "\n")

Print all list:  ['abcd', 786, 2.23, 'john', 70.2]
Print list element-0:  abcd
Print list element-1:  786
Print list element-1 until 3:  [786, 2.23]
Print list element-1 until 4:  [786, 2.23, 'john']
Print list element-2 until end:  [2.23, 'john', 70.2]
Print list twice:  [123, 'john', 123, 'john']
Join two list:  ['abcd', 786, 2.23, 'john', 70.2, 123, 'john'] 



In [23]:
list1[1] = 'coba'
list1[1]

'coba'

In [24]:
list1

['abcd', 'coba', 2.23, 'john', 70.2]

In [25]:
# tuple[1] = 'math'
# tuple[1]

### Dictionary

+ jumlahnya 1: {'key': value}
+ jumlahnya lebih dari 1: {'key1': value1, 'key2': value2, 'key3': {'key3.1': value31, 'key3.2': value32}}

In [26]:
dict1 = {}
dict1['one'] = "This is one"
dict1[2] = "This is two"
tinydict = {'name': 'john','code':6734, 'dept': {'pos': 'sales', 'pos': 'engineering'}}

print("Print dictionary on dict1['one']: ", dict1['one'])
print("Print dictionary on dict1[2]: ",dict1[2])
print("Print dictionary on dict1: ", dict1)
print("Print dictionary on tinydict: ", tinydict)
print("Print tinydict dictionary keys: ", tinydict.keys())
print("Print tinydict dictionary values: ", tinydict.values(), "\n")

Print dictionary on dict1['one']:  This is one
Print dictionary on dict1[2]:  This is two
Print dictionary on dict1:  {'one': 'This is one', 2: 'This is two'}
Print dictionary on tinydict:  {'name': 'john', 'code': 6734, 'dept': {'pos': 'engineering'}}
Print tinydict dictionary keys:  dict_keys(['name', 'code', 'dept'])
Print tinydict dictionary values:  dict_values(['john', 6734, {'pos': 'engineering'}]) 



### Numpy

In [27]:
import numpy as np

In [28]:
my_list = [1, 2, 3, 4, 5]

type(my_list)

list

In [29]:
my_list

[1, 2, 3, 4, 5]

In [30]:
my_list_np = np.array(my_list)

type(my_list_np)

numpy.ndarray

In [31]:
my_list_np

array([1, 2, 3, 4, 5])

In [32]:
my_list_np.shape

(5,)

In [33]:
my_list_matrix = np.array([[1, 2, 7], [3, 4, 6]])

my_list_matrix

array([[1, 2, 7],
       [3, 4, 6]])

In [34]:
my_list_matrix.shape

(2, 3)

In [35]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
mat1 = np.array([[1, 2, 7], [3, 4, 6]])
mat2 = np.array([[2, 5, 8], [6, 4, 6], [7, 5, 6]])

np.dot(mat1, mat2)

array([[63, 48, 62],
       [72, 61, 84]])

In [38]:
mat2

array([[2, 5, 8],
       [6, 4, 6],
       [7, 5, 6]])

In [39]:
mat2.shape

(3, 3)

In [40]:
mat2[:, 0]

array([2, 6, 7])

In [41]:
mat2[1, 0:2]

array([6, 4])

In [42]:
mat2[1][1]

4

### Pandas Series and DataFrame

In [43]:
import pandas as pd
from numpy.random import randn

df = pd.DataFrame(randn(5,4), index='1 2 3 4 5'.split(), columns='A B C F'.split())

df

A         B         C         F
1  1.116168 -0.368239  1.942100  0.462124
2  0.146719  0.788501 -0.067893  0.921075
3  0.394733  1.783883 -0.922283  1.578824
4 -1.415826  0.032231 -1.260538 -0.126706
5  1.058948  0.852673  0.382677 -1.637054

In [44]:
df.size

20

In [45]:
df.shape

(5, 4)

In [46]:
df['A']

1    1.116168
2    0.146719
3    0.394733
4   -1.415826
5    1.058948
Name: A, dtype: float64

In [47]:
df.loc[['2', '3'], ['B', 'C']]

B         C
2  0.788501 -0.067893
3  1.783883 -0.922283

In [48]:
df.iloc[:, 1]

1   -0.368239
2    0.788501
3    1.783883
4    0.032231
5    0.852673
Name: B, dtype: float64

In [49]:
df.iloc[2:4, 0]

3    0.394733
4   -1.415826
Name: A, dtype: float64

# Logic

In [50]:
nama = 'Sasuke'
umur = 10
jomblo = False

### If

In [51]:
if jomblo == True:
    print("Sasuke jomblo")

### If Else

In [52]:
if jomblo == True:
    print("Sasuke jomblo")
else:
    print("Sasuke tidak jomblo")

Sasuke tidak jomblo


AND 
1 & 1 = True
1 & 0 = False
0 & 1 = False
0 & 0 = False

AND 
1 & 1 = True
1 & 0 = True
0 & 1 = True
0 & 0 = False


### And

In [53]:
if umur > 17:
    print("Sasuke Dewasa")
elif umur > 14 and umur < 17:
    print("Sasuke Remaja")
else:
    print("Sasuke Kecil")

Sasuke Kecil


### Or

In [54]:
if umur > 17:
    print("Sasuke Dewasa")
elif umur > 14 or umur < 17:
    print("Sasuke Remaja")
else:
    print("Sasuke Kecil")

Sasuke Remaja


In [55]:
buah = ["nanas", "apel", "pepaya", "manggis"]

if buah[1] == "manggis":
    print("True")
else:
    print("False")

False


In [56]:
matrix1 = np.array([[1, 2, 7], [3, 4, 6]])

matrix1

array([[1, 2, 7],
       [3, 4, 6]])

In [57]:
if matrix1[1][1] == 4:
    print("True")
else:
    print("False")

True


# Loop atau Perulangan

In [58]:
fruits = ["nanas", "pisang", "semangka", "apple"]

## For

In [59]:
for fruit in fruits:
    print(fruit)

nanas
pisang
semangka
apple


In [60]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [61]:
for i, fruit in enumerate(fruits):
    print(f'{fruit} buah ke {i}')

nanas buah ke 0
pisang buah ke 1
semangka buah ke 2
apple buah ke 3


## While

In [62]:
count = 0

while (count < 9):
   print('The count is:', count)
   count = count + 1

print("\nGood bye!")

The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5
The count is: 6
The count is: 7
The count is: 8

Good bye!


### Break

In [63]:
for letter in 'Python':
    print("Current Letter :", letter)
    
    if letter == 'h':
        break

Current Letter : P
Current Letter : y
Current Letter : t


In [64]:
var = 10

while var > 0:
    var = var - 1
    print("Current variable value :", var)
    
    if var == 5:
        break

Current variable value : 9
Current variable value : 8
Current variable value : 7
Current variable value : 6
Current variable value : 5


### Pass

In [65]:
for letter in 'Python':
    if letter == 'h':
        pass
        print('This is pass block')
        
    print('Current Letter :', letter)

Current Letter : P
Current Letter : y
Current Letter : t
This is pass block
Current Letter : h
Current Letter : o
Current Letter : n

Good bye!


# Function

### Void Function

In [ ]:
def print_coba

### Function with Return value

In [68]:
def perkalian(a, b):
    hasil_kali = a * b
    return hasil_kali

In [69]:
perkalian(10, 2)

20

In [ ]:
def kali_bagi(a, b):
    hasil_kali = a * b
    hasil_bagi = a / b
    return hasil_kali, hasil_bagi

In [ ]:
hasil_kali, hasil_bagi = kali_bagi(10, 2)

print(hasil_kali)
print(hasil_bagi)